### PR TITLE
SL-23 Add Graham A to DB

### PR DESCRIPTION
**Pull request by chuckinchucks**

### CODE REVIEW

**Review by slimwizard — CHANGES_REQUESTED** [review]
Mostly looks good. Still need to update the Angular tests to account for the changes to the component.

**Review by Jfrachal — COMMENTED** [review]
Looks good on review, the only thing that I see that needs update are the angular test changes requested by Matt. Those were changed in the e2e test recent push.

**Comment by slimwizard** [comment]
looks good from here. Just be careful when resolving the conflicts before merging.

**Review by slimwizard — APPROVED** [review]

**Comment by grant-freeman** [comment]
i would really recommend merging dev into this before this gets merged. also ensuring that everything in the nethkena component that was added this sprint is in this change will reduce headaches.

**Review by grant-freeman — APPROVED** [review]
looks fine

**Pull request merged**
